### ISSUE TITLE
Suggestion: Add IPv6 capability

### ISSUE THREAD

**Issue by ThomasLandauer** [jbboehr/dnsbl.php#5]
What about adding compatibility for IPv6 addresses?

IMO, all that needs to be done would be to add the reversing to [`DNSBL::reverseIp()`](https://github.com/jbboehr/dnsbl.php/blob/master/src/DNSBL.php#L224). I've just checked out the code from https://stackoverflow.com/a/6621473/1668200 and it looks fine at first sight - so this should be easy to integrate.

What do you think? Should I create a PR?

**Comment by jbboehr** [comment]
I haven't used this library for years, I just keep the tests passing on the latest PHP, but I'd be glad to merge IPv6 support if you'd like to work on it.
